language: php

php:
  - 5.6

sudo: false

env:
  matrix:
      - DRIVER_VERSION=1.1.2 SERVER_VERSION=2.4
  global:
    - KEY_SERVER="hkp://keyserver.ubuntu.com:80"
    - MONGO_REPO_URI="http://repo.mongodb.com/apt/ubuntu"
    - MONGO_REPO_TYPE="precise/mongodb-enterprise/"
    - SOURCES_LOC="/etc/apt/sources.list.d/mongodb.list"
    - MONGODB_VERSION=2.6.10

before_install:
  - wget http://fastdl.mongodb.org/linux/mongodb-linux-x86_64-$MONGODB_VERSION.tgz
  - tar xfz mongodb-linux-x86_64-$MONGODB_VERSION.tgz
  - export PATH=`pwd`/mongodb-linux-x86_64-$MONGODB_VERSION/bin:$PATH
  - mkdir -p data/db
  - mongod --dbpath=data/db &
  - sleep 3

before_script:
  - phpenv config-rm xdebug.ini
  - if dpkg --compare-versions ${SERVER_VERSION} le "2.4"; then export SERVER_SERVICE=mongodb; else export SERVER_SERVICE=mongod; fi
  - if ! nc -z localhost 27017; then sudo service ${SERVER_SERVICE} start; fi
  - mongod --version
  - pecl install -f mongodb-${DRIVER_VERSION}
  - if [ "$(php -v | grep 'PHP 5.4')" ]; then echo 'extension = mongodb.so' >> ~/.phpenv/versions/$(phpenv version-name)/etc/php.ini; fi
  - php --ri mongodb
  - composer install --dev --no-interaction --prefer-source
  - ulimit -c
  - ulimit -c unlimited -S
  - /home/travis/.phpenv/versions/5.6/bin/composer self-update
  - composer self-update
  - cp .env.travis .env
  - composer install --prefer-source --no-interaction --dev
  - php artisan key:generate
  - mysql -e 'create database IF NOT EXISTS  cineacademy;'   -uroot
  - mysql -uroot cineacademy < mysql/cineacademy.sql
  - php artisan  db:seed

script: phpunit

cache:
  directories:
    - $HOME/.composer/cache

notifications:
  email:
    - julien@meetserious.com


services:
  - redis-server
  - elasticsearch
  - mongodb
  - mysql
